In [3]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd

plt.style.use("fivethirtyeight")

In [2]:
!pip install joblib

  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)


In [12]:
class Perceptron:
    def __init__(self,eta: float=None,epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta=eta  #Learning rate
        self.epochs=epochs  #number of interations
        
    def fit(self, X, y):
        self.X=X
        self.y=y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X with bias: \n{X_with_bias}")
        

In [17]:
obj=Perceptron(eta=0.01,epochs=10)

In [18]:
obj.eta

0.01

In [19]:
obj.epochs

10

In [20]:
obj.weights

array([1.16125092e-04, 1.13975201e-04, 5.79186604e-05])

In [24]:
X=np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
y=np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [26]:
obj.fit(X,y)

X with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
